### ISSUE TITLE
Конфликт с locationselector

### ISSUE THREAD

**Issue by dkodnik** [Alex300/RegionCity#1]
Если стоит плагин locationselector, то скорее из-за конфликта - не работает сайт.

`Fatal error: Cannot redeclare cot_getlocation() (previously declared in /var/wwwl/plugins/locationselector/inc/locationselector.functions.php:161) in /var/www/plugins/regioncity/regioncity.global.php on line 95`

**Comment by Alex300** [comment]
Этот плагин и появился давно из "locationselector". А зачем вообще ставить на сайт два плагина, делающих одно и тоже (только по разному)?
